name = "OrbifolderBridge"
uuid = "3acbec13-77c2-4490-8e9e-4fb654d4e382"
authors = ["xiupos <me@xiupos.net> and contributors"]
version = "1.0.0-DEV"

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
julia = "1.10.10"
Preferences = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
